# Generated by Django 4.0.2 on 2022-02-13 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('work_email', models.EmailField(max_length=60, null=True, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250, null=True)),
                ('position', models.CharField(max_length=200, null=True)),
                ('marital_status', models.CharField(max_length=150, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('hire_date', models.DateTimeField()),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('permission', models.CharField(choices=[('EMP', 'Employee'), ('LEAD', 'Team Lead'), ('MNGR', 'Manager'), ('SPRMGR', 'Super Manager')], default='EMP', max_length=8)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('mentor', models.ManyToManyField(related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('announcement_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ProficiencyLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(choices=[('BEG', 'Beginner'), ('INT', 'Intermediate'), ('ADV', 'Advanced'), ('EXP', 'Expert')], max_length=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('short_description', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('projected_end_date', models.DateTimeField()),
                ('actual_end_date', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('PUB', 'Public'), ('PRI', 'Private')], default='PUB', max_length=3)),
                ('project_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project_to_announcement', models.ManyToManyField(to='djangoresourcemanagement.Announcements')),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(null=True, upload_to='resources/')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(null=True)),
                ('link', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=100)),
                ('long_description', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SquadMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djangoresourcemanagement.roles')),
            ],
        ),
        migrations.CreateModel(
            name='TechSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserToSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('skill_status', models.CharField(choices=[('APP', 'Approved'), ('PEN', 'Pending'), ('REJ', 'Rejected')], default='PEN', max_length=10)),
                ('skill_status_reason', models.CharField(max_length=255)),
                ('date_modified_status', models.DateTimeField()),
                ('proficiency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djangoresourcemanagement.proficiencylevels')),
                ('projects_that_show_experience_of_skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djangoresourcemanagement.projects')),
                ('skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djangoresourcemanagement.techskill')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='techskill',
            name='user_to_skill',
            field=models.ManyToManyField(through='djangoresourcemanagement.UserToSkill', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('short_description', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('team_creation_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('PUB', 'Public'), ('PRI', 'Private')], default='PUB', max_length=3)),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader', to=settings.AUTH_USER_MODEL)),
                ('team_announcements', models.ManyToManyField(to='djangoresourcemanagement.Announcements')),
                ('team_members', models.ManyToManyField(through='djangoresourcemanagement.SquadMembers', to=settings.AUTH_USER_MODEL)),
                ('team_projects', models.ManyToManyField(to='djangoresourcemanagement.Projects')),
                ('team_resources', models.ManyToManyField(to='djangoresourcemanagement.Resources')),
            ],
        ),
        migrations.AddField(
            model_name='squadmembers',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djangoresourcemanagement.teams'),
        ),
        migrations.AddField(
            model_name='squadmembers',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_to_resource',
            field=models.ManyToManyField(to='djangoresourcemanagement.Resources'),
        ),
        migrations.AddField(
            model_name='announcements',
            name='announcement_to_resource',
            field=models.ManyToManyField(to='djangoresourcemanagement.Resources'),
        ),
        migrations.AddField(
            model_name='announcements',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='users',
            name='user_project',
            field=models.ManyToManyField(to='djangoresourcemanagement.Projects'),
        ),
    ]
