# Generated by Django 4.0.2 on 2022-02-16 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoresourcemanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoskill',
            name='date_modified_status',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='usertoskill',
            name='skill_status_reason',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
