# Generated by Django 4.0.2 on 2022-02-16 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoresourcemanagement', '0002_alter_usertoskill_date_modified_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mentor',
            field=models.ManyToManyField(null=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='users',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
