# Generated by Django 4.0.2 on 2022-02-16 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoresourcemanagement', '0005_alter_users_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
